kind: pipeline
type: docker
name: mkube-web-publish

environment:
  GOOS: linux
  GOARCH: amd64

steps:
  - name: build
    image: plugins/docker:20.14.2
    volumes:
      - name: hosts
        path: /etc/hosts
      - name: docker-ca
        path: /etc/docker
      - name: dockersock
        path: /var/run/docker.sock
    settings:
      username: admin
      password:
        from_secret: harbor_password
      repo: harbor.codehrose.com/mkube/mkube-web
      registry: harbor.codehrose.com
      tags:
        - v1.7
  - name: ssh commands
    image: appleboy/drone-ssh:1.6.13
    settings:
      host: 192.168.1.19
      username: root
      password:
        from_secret: ssh_password
      port: 22
      script:
        #拉取镜像并重启 注意--需要提前在目标主机完成docker login
        - if [ $(docker ps -a | grep mkube-web | wc -l) -ge 1 ];then docker stop mkube-web && docker rm mkube-web; fi
        - docker pull harbor.codehrose.com/mkube/mkube-web:v1.1
        - export BACKEND_HOST=http://192.168.1.3:8882/
        - docker run --name mkube-web --restart=always -d -p8081:80 -e BACKEND_HOST=$BACKEND_HOST harbor.codehrose.com/mkube/mkube-web:v1.1
volumes:
  - name: hosts
    host:
      path: /etc/hosts
  - name: docker-ca
    host:
      path: /etc/docker
  - name: dockersock
    host:
      path: /var/run/docker.sock
